/* SCHEMA DES TABLES DE REFERENCE DU CLIENT */
CREATE SCHEMA [REF]
    AUTHORIZATION [dbo];
GO

/* SCHEMA DES VUES DU REFERENTIEL CLIENT */
CREATE SCHEMA [SYNCH]
    AUTHORIZATION [dbo];
GO

/* SCHEMA DES TABLES GERANT LES PROCESSUS DU CLIENT */
CREATE SCHEMA [PROC]
    AUTHORIZATION [dbo];
GO
